### ISSUE TITLE
E3 RRF IDEX 1.0 Fan0 Fan1 no power

### ISSUE THREAD

**Issue by Cowbite** [bigtreetech/BTT-E3-RRF#30]
I'm getting no power to these fan headers - Fan0 and Fan1 on the idex board. Should they just work or do they need turning on in the firmware?
I'm currently using it for a second z axis on an Ender 3, so it's setup and working as far as that goes.

**Comment by trengtor** [comment]
Neeg config in FW

**Comment by Cowbite** [comment]
Problem wasn't with the board or firmware. Wiring issue.
